apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: frontend
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: backend
    env: dev
spec:
  containers:
  - name: node
    image: node:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3
  labels:
    app: database
    env: dev
spec:
  containers:
  - name: mysql
    image: mysql:alpine