apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: dev
  name: dev-resource-quota
spec:
  hard:
    limits.cpu: "4"
    limits.memory: 4Gi
    requests.cpu: "2"
    requests.memory: 2Gi
    pods: "2"