apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-gateway-nestjs-rs
  labels:
    app: api-gateway-nestjs-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway-nestjs-pod
  template:
    metadata:
      labels:
        app: api-gateway-nestjs-pod
    spec:
      containers:
      - name: api-gateway-nestjs
        image: gmahechas/api-gateway-nestjs
        imagePullPolicy: IfNotPresent
        ports:  
          - containerPort: 3000