apiVersion: v1
kind: Service
metadata:
  name: api-gateway-nestjs-service
spec:
  type: NodePort
  selector:
    app: api-gateway-nestjs-pod
  ports:
    - protocol: TCP
      port: 3050
      targetPort: 3000
      nodePort: 31515